/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.*;
import Modelo.DAO.*;
import Modelo.VO.*;
import Facade.*;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 *
 * @author kike6 Actualizacion 2
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }
    
    /*public class Principal extends JFrame implements ActionListener{
        
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        btnsello = new javax.swing.JButton();
        menui = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        PersonMIt = new javax.swing.JMenuItem();
        turnomIt = new javax.swing.JMenuItem();
        puestomIt = new javax.swing.JMenuItem();
        jmclientes = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        sucursalmIt = new javax.swing.JMenuItem();
        tipentregamIt = new javax.swing.JMenuItem();
        tippagomIt = new javax.swing.JMenuItem();
        jmtinventario = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        empleti = new javax.swing.JMenuItem();
        jmitproductor = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jmiventa = new javax.swing.JMenuItem();
        jmtventadetalle = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        productosmIt = new javax.swing.JMenuItem();
        jmientradas = new javax.swing.JMenuItem();
        jmentradadeta = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jmtbusvent = new javax.swing.JMenuItem();
        jmItauditoria = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 663, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 429, Short.MAX_VALUE)
        );

        btnsello.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/IMG-20200728-WA0036 (4).jpg"))); // NOI18N
        btnsello.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnselloActionPerformed(evt);
            }
        });

        jMenu1.setText("Personas");

        PersonMIt.setText("Personas");
        PersonMIt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PersonMItActionPerformed(evt);
            }
        });
        jMenu1.add(PersonMIt);

        turnomIt.setText("Turno");
        turnomIt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                turnomItActionPerformed(evt);
            }
        });
        jMenu1.add(turnomIt);

        puestomIt.setText("Puesto");
        puestomIt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puestomItActionPerformed(evt);
            }
        });
        jMenu1.add(puestomIt);

        jmclientes.setText("Clientes");
        jmclientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmclientesActionPerformed(evt);
            }
        });
        jMenu1.add(jmclientes);

        menui.add(jMenu1);

        jMenu2.setText("Sucursal");

        sucursalmIt.setText("Sucursal");
        sucursalmIt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sucursalmItActionPerformed(evt);
            }
        });
        jMenu2.add(sucursalmIt);

        tipentregamIt.setText("Tipo Entrega");
        tipentregamIt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipentregamItActionPerformed(evt);
            }
        });
        jMenu2.add(tipentregamIt);

        tippagomIt.setText("Tipo Pago");
        tippagomIt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tippagomItActionPerformed(evt);
            }
        });
        jMenu2.add(tippagomIt);

        jmtinventario.setText("Inventario");
        jmtinventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmtinventarioActionPerformed(evt);
            }
        });
        jMenu2.add(jmtinventario);

        menui.add(jMenu2);

        jMenu4.setText("Empleados");

        empleti.setText("Empleados");
        empleti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empletiActionPerformed(evt);
            }
        });
        jMenu4.add(empleti);

        jmitproductor.setText("Productor");
        jmitproductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmitproductorActionPerformed(evt);
            }
        });
        jMenu4.add(jmitproductor);

        menui.add(jMenu4);

        jMenu5.setText("Ventas");

        jmiventa.setText("Ventas");
        jmiventa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiventaActionPerformed(evt);
            }
        });
        jMenu5.add(jmiventa);

        jmtventadetalle.setText("Venta de talle");
        jmtventadetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmtventadetalleActionPerformed(evt);
            }
        });
        jMenu5.add(jmtventadetalle);

        menui.add(jMenu5);

        jMenu3.setText("Productos");

        productosmIt.setText("Productos");
        productosmIt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productosmItActionPerformed(evt);
            }
        });
        jMenu3.add(productosmIt);

        jmientradas.setText("Entradas");
        jmientradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmientradasActionPerformed(evt);
            }
        });
        jMenu3.add(jmientradas);

        jmentradadeta.setText("Entrada Detalles");
        jmentradadeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmentradadetaActionPerformed(evt);
            }
        });
        jMenu3.add(jmentradadeta);

        menui.add(jMenu3);

        jMenu6.setText("Busqueda");

        jmtbusvent.setText("Busqueda de Ventas");
        jmtbusvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmtbusventActionPerformed(evt);
            }
        });
        jMenu6.add(jmtbusvent);

        jmItauditoria.setText("Auditoria");
        jmItauditoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmItauditoriaActionPerformed(evt);
            }
        });
        jMenu6.add(jmItauditoria);

        menui.add(jMenu6);

        setJMenuBar(menui);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnsello, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 39, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnsello)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PersonMItActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PersonMItActionPerformed
        VoPersonas voper = new VoPersonas();
        DaoPersonas daoper = new DaoPersonas();
        Persona frmper = new Persona();
        CtrlPersonas ctrlper = new CtrlPersonas(voper,daoper,frmper);
        
        ctrlper.iniciar();
        panel.add(frmper);
        frmper.show();
        //frmper.setVisible(true);
    }//GEN-LAST:event_PersonMItActionPerformed

    private void turnomItActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turnomItActionPerformed
        VoTurno votu = new VoTurno();
        DaoTurno datu = new DaoTurno();
        Turno frmtu = new Turno();
        CtrlTurno ctrlt = new CtrlTurno(votu,datu,frmtu);
        ctrlt.iniciar();
        panel.add(frmtu);
        frmtu.show();
    }//GEN-LAST:event_turnomItActionPerformed

    private void puestomItActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puestomItActionPerformed
        VoPuestos voPu = new VoPuestos();
        DaoPuestos daopu = new DaoPuestos();
        Puesto frmpues = new Puesto();
        CtrlPuesto ctrl = new CtrlPuesto(voPu,daopu,frmpues);
        ctrl.iniciar();
        panel.add(frmpues);
        frmpues.show();
    }//GEN-LAST:event_puestomItActionPerformed

    private void sucursalmItActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sucursalmItActionPerformed
        VoSucursal votsu = new VoSucursal();
        DaoSucursal daosu = new DaoSucursal();
        Sucursales frmsu = new Sucursales();
        CtrlSucursal ctrlsu = new CtrlSucursal(votsu,daosu,frmsu);
        ctrlsu.iniciar();
        panel.add(frmsu);
        frmsu.show();
    }//GEN-LAST:event_sucursalmItActionPerformed

    private void tipentregamItActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipentregamItActionPerformed

        VoTipoentrega votip = new VoTipoentrega();
        DaoTipoentrega daotip = new DaoTipoentrega();
        Tipoentrega frmtip = new Tipoentrega();
        CtrlTipoentrega ctrltip = new CtrlTipoentrega(votip,daotip,frmtip);
        ctrltip.iniciar();
        panel.add(frmtip);
        frmtip.show();
    }//GEN-LAST:event_tipentregamItActionPerformed

    private void tippagomItActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tippagomItActionPerformed
        VoTipopago votipp = new VoTipopago();
        DaoTipopago daotipp = new DaoTipopago();
        Tipopagos tippago = new Tipopagos();
        CtrlTipopago ctrltipp = new CtrlTipopago(votipp,daotipp,tippago);
        ctrltipp.iniciar();
        panel.add(tippago);
        tippago.show();
    }//GEN-LAST:event_tippagomItActionPerformed

    private void productosmItActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productosmItActionPerformed
        VoProductos vopro = new VoProductos();
        DaoProductos daopro = new DaoProductos();
        Producto frmpro = new Producto();
        CtrlProductos ctrlpro = new CtrlProductos(vopro,daopro,frmpro);
        ctrlpro.iniciar();
        panel.add(frmpro);
        frmpro.show();
        
    }//GEN-LAST:event_productosmItActionPerformed

    private void empletiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empletiActionPerformed
        VoEmpleados voemple = new VoEmpleados();
        DaoEmpleados daoemple = new DaoEmpleados();
        Empleados frmemple = new Empleados();
        CtlEmpleados ctrlempl = new CtlEmpleados(voemple,daoemple,frmemple);
        ctrlempl.iniciar();
        panel.add(frmemple);
        frmemple.show();
    }//GEN-LAST:event_empletiActionPerformed

    private void jmientradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmientradasActionPerformed
        VoEntradas voentra = new VoEntradas();
        DaoEntradas daoentr = new DaoEntradas();
        Entradas frmentr = new Entradas();
        CtrlEntradas ctrlen = new CtrlEntradas(voentra,daoentr,frmentr);
        ctrlen.iniciar();
        panel.add(frmentr);
        frmentr.show();
    }//GEN-LAST:event_jmientradasActionPerformed

    private void jmentradadetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmentradadetaActionPerformed
        VoEntradaDetalles voed = new VoEntradaDetalles();
        DaoEntradadetalles daoed = new DaoEntradadetalles();
        EntradaDetalle frmed = new EntradaDetalle();
        CtrlEntradadetalles ctrled = new CtrlEntradadetalles(voed,daoed,frmed);
        ctrled.iniciar();
        panel.add(frmed);
        frmed.show();
    }//GEN-LAST:event_jmentradadetaActionPerformed

    private void jmtinventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmtinventarioActionPerformed
        VoInventario voin = new VoInventario();
        DaoInventario daoin = new DaoInventario();
        Inventario frminv = new Inventario();
        CtrlInventario ctrlinv = new CtrlInventario(voin,daoin,frminv);
        ctrlinv.iniciar();
        panel.add(frminv);
        frminv.show();
    }//GEN-LAST:event_jmtinventarioActionPerformed

    private void jmitproductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmitproductorActionPerformed
        VoProductores vopro = new VoProductores();
        DaoProductor daopro= new DaoProductor();
        Productores frmprod = new Productores();
        CtrlProductor ctrlpro = new CtrlProductor(vopro,daopro,frmprod);
        ctrlpro.iniciar();
        panel.add(frmprod);
        frmprod.show();
        
        
    }//GEN-LAST:event_jmitproductorActionPerformed

    private void jmclientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmclientesActionPerformed
        VoClientes vocli = new VoClientes();
        DaoClientes daocli = new DaoClientes();
        Clientes frmcli = new Clientes();
        CtrlClientes ctrlcli = new CtrlClientes(vocli,daocli,frmcli);
        ctrlcli.iniciar();
        panel.add(frmcli);
        frmcli.show();
    }//GEN-LAST:event_jmclientesActionPerformed

    private void jmiventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiventaActionPerformed
        VoVentas voven = new VoVentas();
        DaoVentas daoven = new DaoVentas();
        Ventas frmven = new Ventas();
        CtrlVentas ctrlven = new CtrlVentas(voven,daoven,frmven);
        ctrlven.iniciar();
        panel.add(frmven);
        frmven.show();
    }//GEN-LAST:event_jmiventaActionPerformed

    private void jmtventadetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmtventadetalleActionPerformed
        VoVentaDetalle voVD = new VoVentaDetalle();
        DaoVentaDetalle daoVD = new DaoVentaDetalle();
        VentaDetalle frmVD = new VentaDetalle();
        CtrlVentaDetalle ctrlven = new CtrlVentaDetalle(voVD,daoVD,frmVD);
        ctrlven.iniciar();
        panel.add(frmVD);
        frmVD.show();
    }//GEN-LAST:event_jmtventadetalleActionPerformed

    private void jmtbusventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmtbusventActionPerformed
        BusquedaVentas frmbus = new BusquedaVentas();
        panel.add(frmbus);
        frmbus.show();
    }//GEN-LAST:event_jmtbusventActionPerformed

    private void jmItauditoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmItauditoriaActionPerformed
        Auditoria frmaud = new Auditoria();
        panel.add(frmaud);
        frmaud.show();
    }//GEN-LAST:event_jmItauditoriaActionPerformed

    private void btnselloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnselloActionPerformed

        JOptionPane.showMessageDialog(null,"        "+" Esta aplicasionse ejecuta con acceso restringido \n y no pone en riesgo  su computadora y su informacion personal","digicert",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnselloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem PersonMIt;
    private javax.swing.JButton btnsello;
    private javax.swing.JMenuItem empleti;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuItem jmItauditoria;
    private javax.swing.JMenuItem jmclientes;
    private javax.swing.JMenuItem jmentradadeta;
    private javax.swing.JMenuItem jmientradas;
    private javax.swing.JMenuItem jmitproductor;
    private javax.swing.JMenuItem jmiventa;
    private javax.swing.JMenuItem jmtbusvent;
    private javax.swing.JMenuItem jmtinventario;
    private javax.swing.JMenuItem jmtventadetalle;
    private javax.swing.JMenuBar menui;
    private javax.swing.JPanel panel;
    private javax.swing.JMenuItem productosmIt;
    private javax.swing.JMenuItem puestomIt;
    private javax.swing.JMenuItem sucursalmIt;
    private javax.swing.JMenuItem tipentregamIt;
    private javax.swing.JMenuItem tippagomIt;
    private javax.swing.JMenuItem turnomIt;
    // End of variables declaration//GEN-END:variables
}
